### ISSUE TITLE
Is it possible to implement custom logic?

### ISSUE THREAD

**Issue by ekkis** [okbob/plpgsql_lint#5]
I'm working with Greenplum, an MPP system built atop Postgres, and am looking for a linter for the SQL developers write where I can write my own rules.  would it be possible to do that with this project?

**Comment by okbob** [comment]
Hi

2016-03-30 23:25 GMT+02:00 Erick Calder notifications@github.com:

> I'm working with Greenplum, an MPP system built atop Postgres, and am
> looking for a linter for the SQL developers write where I can write my own
> rules. would it be possible to do that with this project?

plpgsql_lint is obsolete. Now the plpgsql_check is living
https://github.com/okbob/plpgsql_check, But plpgsql_check requires
PostgreSQL 9.2.

This code is not designed be extensible - it is C extension. if you need
some private or public changes, you can do own fork. It requires C code.
This code is released under BSD licence so any modification and commercial
usage is available. Same licence was used for plpgsql_lint.

Regards

Pavel

**Comment by ekkis** [comment]
thanks Pavel.  I think it's not going to be feasible for me.
