### ISSUE TITLE
How to run on Windows 10

### ISSUE THREAD

**Issue by hoa-nx** [okbob/plpgsql_lint#6]
This extension can run on Windows 10?
Please help me how to build and run on Windows OS? 
Thanks,

**Comment by okbob** [comment]
Hi

2018-07-12 10:09 GMT+02:00 thieu-nx <notifications@github.com>:

> This extension can run on Windows 10?
> Please help me how to build and run on Windows OS?
> Thanks,
>
This extension is deprecated, and it is not maintained more.

You should to use plpgsql_check instead - it is next generation of
plpgsql_check.

It can work on Window 10 - https://github.com/okbob/plpgsql_check

http://okbob.blogspot.com/2017/10/plpgsqlcheck-122-for-windows.html#links

**Comment by hoa-nx** [comment]
thanks
